apiVersion: v1
kind: Service
metadata:
  name: global-chat-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: global-chat-service
    tier: backend
spec:
  selector:
    app: global-chat-service
  ports:
  - port: 8070
    targetPort: 8070
    protocol: TCP
    name: http
  type: ClusterIP
