apiVersion: v1
kind: Service
metadata:
  name: notification-integration-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: notification-integration-service
    tier: backend
spec:
  selector:
    app: notification-integration-service
  ports:
  - port: 8060
    targetPort: 8060
    protocol: TCP
    name: http
  type: ClusterIP
