apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ${K8S_NAMESPACE}
  labels:
    app: auth-service
    tier: backend
spec:
  selector:
    app: auth-service
  ports:
  - port: 8010
    targetPort: 8010
    protocol: TCP
    name: http
  type: ClusterIP
