apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: ${K8S_NAMESPACE}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-orchestration-service
  namespace: ${K8S_NAMESPACE}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-integration-service
  namespace: ${K8S_NAMESPACE}
