apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: ${K8S_NAMESPACE}
data:
  vault-config.json: |
    {
      "backend": {
        "file": {
          "path": "/vault/file"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "ui": true,
      "disable_mlock": true
    }
